### ISSUE TITLE
How to compile project on Windows 10 x64

### ISSUE THREAD

**Issue by thelittlepony** [Glebanister/ample#92]
Hello, i'm using Windows 10 x64, and how to i compile this project?
Linux on my PC is NOT SUPPORTED.
Please help!!!!

**Comment by Glebanister** [comment]
> Hello, i'm using Windows 10 x64, and how to i compile this project? Linux on my PC is NOT SUPPORTED. Please help!!!!

 Hi! Unfortunately, our project does not support Windows

**Comment by thelittlepony** [comment]
Hello, well, thank you for response
